config/routes.rb
Rails.application.routes.draw do
  resources :produtos
  resources :pedidos
  resources :items
  resources :funcionarios
  resources :fornecedors
  resources :comandas do
    member do
      get 'cancelar_pedido'
      get 'finalizar_pedido'
      post 'encerrar'
      post 'new_pedido'
    end
  end
  post 'comandas/create'
  get 'sessions/new'

  
  root                'static_pages#home'
  get    'home'    => 'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get    'logout'  => 'sessions#destroy'
  
  
  get 'fornecedor/search' => 'fornecedors#search'
  post 'fornecedor/search' => 'fornecedors#search', as: :fornecedors_search
  get 'fornecedor/relatorio/:id' => 'fornecedors#relatorio', as: :fornecedors_relatorio
  get 'fornecedor/del_fornecedor/:id', to: 'fornecedors#destroy', as: :fornecedor_delete
  
  
  get 'funcionario/search' => 'funcionarios#search'
  post 'funcionario/search' => 'funcionarios#search', as: :funcionarios_search
  get 'funcionario/demitir/:id' => 'funcionarios#demitir', as: :funcionarios_demitir

  get 'pedidos' => 'pedidos#index', as: :pedido_index
  get 'pedido/:id' => 'pedidos#show', as: :pedido_show
  get 'pedido/:id/finalizar_pedido' => 'pedidos#finalizar_pedido', as: :pedido_encerrar
  
  get 'compra/item_index', to: 'compra#item_index', as: :item_index
  post 'compra/item_index', to: 'compra#item_index'
  post 'compra/item(/:id)', to: 'compra#item_create'
  patch 'compra/item/:id', to: 'compra#item_update'
  get 'compra/item(/:id)', to: 'compra#item_show', as: :item_show
  get 'compra/item_new', to: 'compra#item_new', as: :item_new
  get 'compra/item/:id/edit', to: 'compra#item_edit', as: :item_edit
  get 'compra/delitem/:id', to: 'compra#item_destroy', as: :item_delete
  get 'compra/relatorio_itens_falta' => 'compra#relatorio_itens_falta', as: :itens_falta_relatorio

  get 'compra/vende_index', to: 'compra#index', as: :vende_index
  post 'compra/vende((/:id1)(/:id2)(/:id3))', to: 'compra#create'
  patch 'compra/vende/:id1/:id2/:id3', to: 'compra#update'
  get 'compra/vende((/:id1)(/:id2)(/:id3))', to: 'compra#show', as: :vende_show
  get 'compra/vende_new', to: 'compra#new', as: :vende_new
  get 'compra/vende/:id1/:id2/:id3/edit', to: 'compra#edit', as: :vende_edit
  get 'compra/delvende/:id1/:id2/:id3', to: 'compra#destroy', as: :vende_delete

  get 'produtos/index', to: 'produtos#index', as: :produto_index
  post 'produtos(/:id)', to: 'produtos#create'
  patch 'produtos/:id', to: 'produtos#update'
  get 'produtos/new', to: 'produtos#new', as: :produto_new
  get 'produtos(/:id)', to: 'produtos#show', as: :produto_show
  get 'produtos/:id/edit', to: 'produtos#edit', as: :produto_edit
  get 'produtos/delproduto/:id', to: 'produtos#destroy', as: :produto_delete

  get 'produto/:produto_id/componentes_index', to: 'produtos#componentes_index', as: :componentes_index
  post 'produto/componentes((/:id1)(/:id2)(/:id3))', to: 'produtos#componentes_create'
  patch 'produto/componentes/:id1/:id2/:id3', to: 'produtos#componentes_update'
  get 'produto/componentes((/:id1)(/:id2)(/:id3))', to: 'produtos#componentes_show', as: :componentes_show
  get 'produtos/componentes_new', to: 'produtos#componentes_new', as: :componentes_new
  get 'produtos/componentes/:id1/:id2/:id3/edit', to: 'produtos#componentes_edit', as: :componentes_edit
  get 'produto/componentes/delcomponente/:id', to: 'produtos#componentes_destroy', as: :componentes_delete

end

app/models/fornecedor.rb
class Fornecedor < ActiveRecord::Base
  has_many :vende, foreign_key: "idFornecedor"
  has_many :items, ->{uniq}, through: :vende
 
  validates_presence_of :nome, :on => :create, :message => "O campo nome deve ser informado"
  validates_presence_of :cnpj, :on => :create, :message => "O campo CNPJ deve ser informado"
  validates_presence_of :cidade, :on => :create, :message => "O campo cidade deve ser informado"
  validates_presence_of :estado, :on => :create, :message => "O campo estado deve ser informado"
  validates_presence_of :telefone, :on => :create, :message => "O campo telefone deve ser informado"
end

app/controllers/fornecedors_controller.rb
class FornecedorsController < ApplicationController
  include ApplicationHelper
  before_action do redirecionar_privilegio(0) end
  before_action :set_fornecedor, only: [:show, :edit, :update, :destroy, :relatorio]

  # GET /fornecedors
  # GET /fornecedors.json
  def index
    @fornecedors = Fornecedor.all
  end

  # GET /fornecedors/1
  # GET /fornecedors/1.json
  def show
  end

  # GET /fornecedors/new
  def new
    @fornecedor = Fornecedor.new
  end

  # GET /fornecedors/1/edit
  def edit
  end

  def relatorio
    
  end

  def search
    if (params[fornecedors_search_path].nil? ||
        params[fornecedors_search_path][:nome].empty?)
      nome = nil
    else
      nome = params[fornecedors_search_path][:nome]
    end
    if nome != nil
      @fornecedors = Fornecedor.where("nome like '#{nome}'")
    else
      @fornecedors = Fornecedor.all
    end
  end

  # POST /fornecedors
  # POST /fornecedors.json
  def create
    @fornecedor = Fornecedor.new(fornecedor_params)

    respond_to do |format|
      if @fornecedor.save
        format.html { redirect_to @fornecedor, notice: 'Fornecedor foi criado com sucesso.' }
        format.json { render :show, status: :created, location: @fornecedor }
      else
        format.html { render :new }
        format.json { render json: @fornecedor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fornecedors/1
  # PATCH/PUT /fornecedors/1.json
  def update
    respond_to do |format|
      if @fornecedor.update(fornecedor_params)
        format.html { redirect_to @fornecedor, notice: 'Fornecedor foi atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @fornecedor }
      else
        format.html { render :edit }
        format.json { render json: @fornecedor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fornecedors/1
  # DELETE /fornecedors/1.json
  def destroy
    @fornecedor.destroy
    respond_to do |format|
      format.html { redirect_to fornecedors_url, notice: 'Fornecedor foi removido com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fornecedor
      @fornecedor = Fornecedor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fornecedor_params
      params.require(:fornecedor).permit(:nome, :cnpj, :cidade, :estado, :num, :endereco, :telefone)
    end
end

app/helpers/fornecedors_helper.rb
module FornecedorsHelper
end

app/views/fornecedors/_form.html.erb
<%= form_for(@fornecedor) do |f| %>
  <% if @fornecedor.errors.any? %>
  <div id="error_explanation">
  <h2><%= pluralize(@fornecedor.errors.count, "error") %> prohibited this fornecedor from being saved:</h2>

  <ul>
    <% @fornecedor.errors.full_messages.each do |message| %>
      <li><%= message %></li>
  <% end %>
  </ul>
</div>
  <% end %>
<div class="row">
  <div class="col-md-6" > 
    <%= f.label :nome %><br>
    <%= f.text_field :nome, class: "form-control" %>
  </div>
</div>
<div class="row">
  <div class="col-md-2">
    <%= f.label :cnpj %><br>
    <%= f.text_field :cnpj, class: "form-control" %>
  </div>
</div>
<div class="row">
  <div class="col-md-4">
    <%= f.label :cidade %><br>
    <%= f.text_field :cidade, class: "form-control" %>
  </div>

  <div class="col-md-4">
    <%= f.label :estado %><br>
    <%= f.text_field :estado, class: "form-control" %>
  </div>

  <div class="col-md-4">
    <%= f.label :num %><br>
    <%= f.text_field :num, class: "form-control" %>
  </div>
</div>
<div class="row">
  <div class="col-md-6">
    <%= f.label :endereco %><br>
    <%= f.text_field :endereco, class: "form-control" %>
  </div>
</div>
<div class="row">
  <div class="col-md-2">
    <%= f.label :telefone %><br>
    <%= f.text_field :telefone, class: "form-control" %>
  </div>
</div>
<br/>
<div class="form-actions">
  <%= f.submit class: "btn green" %>
</div>
<% end %>

app/views/fornecedors/_list_items.html.erb
<table class="table table-hover">
  <thead>
    <tr>
	  <th>Nome</th>
      <th>Marca</th>
      <th>Quantidade</th>
      <th>Alerta</th>
      <!--     <th>Opções</th> -->
	  <th colspan="3"></th>
    </tr>
  </thead>
  <br>
  <tbody>
	
	<% items.each do |item| %>
	 
	  <tr>
        <td><%= item.nome %></td>
        <td><%= item.marca %></td>
        <td><%= item.quantidade %></td>
        <td align = "center">
		  <% if(item.quantidade <= item.quantidadeMinima) %><span class="glyphicon glyphicon-exclamation-sign" title="A quantidade de itens esta baixa"></span><% end %>
		</td>
<!--        <td align = "right"> <a href = <%= item_show_path(item)%>> <span class="glyphicon glyphicon-log-in" title="Detalhes"> </a></td>
        <td align = "center"> <a href = <%= item_edit_path(item)%>> <span class="glyphicon glyphicon-edit" title="Modificar"> </a></td>
        <td align = "center"> <a href = <%= item_delete_path(item)%>> <span class="glyphicon glyphicon-remove" title="Remover"> </a></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

app/views/fornecedors/_table.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Cnpj</th>
      <th>Telefone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% fornecedors.each do |fornecedor| %>
      <tr>
        <td><%= fornecedor.nome %></td>
        <td><%= fornecedor.cnpj %></td>
        <td><%= fornecedor.telefone %></td>
        <td><%= link_to fornecedor do %>
          <span class="glyphicon glyphicon-log-in" title="Detalhes">
        <% end %></td>
        <td><%= link_to edit_fornecedor_path(fornecedor) do %>
          <span class="glyphicon glyphicon-edit" title="Modificar">
        <% end %></td>
        <td><%= link_to fornecedor_delete_path(fornecedor) do %>
          <span class="glyphicon glyphicon-remove" title="Remover">
        <% end %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/fornecedors/edit.html.erb
<div class="portlet light">
  <div class="portlet-title">
    <div class="caption font-blue-sunglo">
      <span class="caption-subject bold uppercase">Editando Fornecedor</span>
    </div>
  </div>
  <div class="portlet-body">

    <%= render 'form' %>

    <%= link_to 'Show', @fornecedor %> |
    <%= link_to 'Back', fornecedors_path %>

  </div>
</div>

app/views/fornecedors/index.html.erb
<p id="notice"><%= notice %></p>

<div class="portlet light">
  <div class="portlet-title">
    <div class="caption font-blue-sunglo">
      <span class="caption-subject bold uppercase">Lista de Fornecedores</span>
    </div>
  </div>
  <div class="portlet-body">
    <%= render partial: 'table', locals: {fornecedors: @fornecedors } %>

    <br>

    <%= link_to new_fornecedor_path, class: "btn green" do %>
      <i class="fa fa-plus-circle"></i>
      Novo Fornecedor
    <% end %>

    <%= link_to fornecedors_search_path, class: "btn green" do %>
      <i class="fa fa-search"></i>
      Consulta de fornecedor
    <% end %>
    
  </div>
</div>

app/views/fornecedors/new.html.erb
<div class="portlet light">
  <div class="portlet-title">
    <div class="caption font-blue-sunglo">
      <span class="caption-subject bold uppercase">Novo Fornecedor</span>
    </div>
  </div>
  <div class="portlet-body">

    <%= render 'form' %>

    <%= link_to 'Back', fornecedors_path %>

  </div>
</div>

app/views/fornecedors/relatorio.html.erb
<% content_for :js do%>
  <%= javascript_tag do %>
  function printDiv(divName) {
    var printContents = document.getElementById(divName).innerHTML;
    var originalContents = document.body.innerHTML;

    document.body.innerHTML = printContents;

    window.print();

    document.body.innerHTML = originalContents;
  }
  <% end %>
<% end %>

<div class="portlet light">
  <div class="portlet-title">
    <div class="caption font-blue-sunglo">
      <span class="caption-subject bold uppercase">Relatorio do fornecedor: <%= @fornecedor.nome %></span>
    </div>
  </div>
  <div class="portlet-body">

    <%= link_to 'Imprimir', '',onclick: 'printDiv("print")' %>
    <div id="print">
      <%= render partial: 'list_items.html.erb', locals: {items: @fornecedor.items} %>
    </div>
  </div>
</div>

app/views/fornecedors/search.html.erb
<p id="notice"><%= notice %></p>

<div class="portlet light">
  <div class="portlet-title">
    <div class="caption font-blue-sunglo">
      <span class="caption-subject bold uppercase">Consulta de Fornecedor pelo nome</span>
    </div>
  </div>
  <div class="portlet-body">

    <%= form_for(fornecedors_search_path) do |f| %>
      <div class="col-md-6">
      <%= f.label 'Nome:' %><br>
      <%= f.text_field :nome, class: "form-control" %>
    </div>
    <br/>
    <div class="actions">
      <%= f.submit "Consulta", class: "btn green"%>
    </div>

  <% end %>

    <%= render partial: 'table', locals: {fornecedors: @fornecedors } %>

    <br>
  </div>
</div>

app/views/fornecedors/show.html.erb
<div class="portlet light">
  <div class="portlet-title">
    <div class="caption font-blue-sunglo">
      <span class="caption-subject bold uppercase">Exibindo fornecedor: <%= @fornecedor.nome %></span>
    </div>
  </div>
  <div class="portlet-body">

    <p id="notice"><%= notice %></p>

    <p>
    <strong>Nome:</strong>
    <%= @fornecedor.nome %>
    </p>

    <p>
    <strong>Cnpj:</strong>
    <%= @fornecedor.cnpj %>
    </p>

    <p>
    <strong>Cidade:</strong>
    <%= @fornecedor.cidade %>
    </p>

    <p>
    <strong>Estado:</strong>
    <%= @fornecedor.estado %>
    </p>

    <p>
    <strong>Num:</strong>
    <%= @fornecedor.num %>
    </p>

    <p>
    <strong>Endereco:</strong>
    <%= @fornecedor.endereco %>
    </p>

    <p>
    <strong>Telefone:</strong>
    <%= @fornecedor.telefone %>
    </p>

    <%= link_to 'Edit', edit_fornecedor_path(@fornecedor) %> |
    <%= link_to 'Back', fornecedors_path %>
  </div>
  <br/><br/>
  <div class="portlet-title">
    <div class="caption font-blue-sunglo">
      <span class="caption-subject bold uppercase">Itens desse fornecedor</span>
    </div>
  </div>

  <div class="portlet-body">

    <%= render partial: 'list_items.html.erb', locals: {items: @fornecedor.items} %>

    <%= link_to 'Gerar relatorio', fornecedors_relatorio_path(@fornecedor) %>
  </div>
</div>