config/routes.rb
Rails.application.routes.draw do
  resources :produtos
  resources :pedidos
  resources :items
  resources :funcionarios
  resources :fornecedors
  resources :comandas do
    member do
      get 'cancelar_pedido'
      get 'finalizar_pedido'
      post 'encerrar'
      post 'new_pedido'
    end
  end
  post 'comandas/create'
  get 'sessions/new'

  
  root                'static_pages#home'
  get    'home'    => 'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get    'logout'  => 'sessions#destroy'
  
  
  get 'fornecedor/search' => 'fornecedors#search'
  post 'fornecedor/search' => 'fornecedors#search', as: :fornecedors_search
  get 'fornecedor/relatorio/:id' => 'fornecedors#relatorio', as: :fornecedors_relatorio
  get 'fornecedor/del_fornecedor/:id', to: 'fornecedors#destroy', as: :fornecedor_delete
  
  
  get 'funcionario/search' => 'funcionarios#search'
  post 'funcionario/search' => 'funcionarios#search', as: :funcionarios_search
  get 'funcionario/demitir/:id' => 'funcionarios#demitir', as: :funcionarios_demitir

  get 'pedidos' => 'pedidos#index', as: :pedido_index
  get 'pedido/:id' => 'pedidos#show', as: :pedido_show
  get 'pedido/:id/finalizar_pedido' => 'pedidos#finalizar_pedido', as: :pedido_encerrar
  
  get 'compra/item_index', to: 'compra#item_index', as: :item_index
  post 'compra/item_index', to: 'compra#item_index'
  post 'compra/item(/:id)', to: 'compra#item_create'
  patch 'compra/item/:id', to: 'compra#item_update'
  get 'compra/item(/:id)', to: 'compra#item_show', as: :item_show
  get 'compra/item_new', to: 'compra#item_new', as: :item_new
  get 'compra/item/:id/edit', to: 'compra#item_edit', as: :item_edit
  get 'compra/delitem/:id', to: 'compra#item_destroy', as: :item_delete
  get 'compra/relatorio_itens_falta' => 'compra#relatorio_itens_falta', as: :itens_falta_relatorio

  get 'compra/vende_index', to: 'compra#index', as: :vende_index
  post 'compra/vende((/:id1)(/:id2)(/:id3))', to: 'compra#create'
  patch 'compra/vende/:id1/:id2/:id3', to: 'compra#update'
  get 'compra/vende((/:id1)(/:id2)(/:id3))', to: 'compra#show', as: :vende_show
  get 'compra/vende_new', to: 'compra#new', as: :vende_new
  get 'compra/vende/:id1/:id2/:id3/edit', to: 'compra#edit', as: :vende_edit
  get 'compra/delvende/:id1/:id2/:id3', to: 'compra#destroy', as: :vende_delete

  get 'produtos/index', to: 'produtos#index', as: :produto_index
  post 'produtos(/:id)', to: 'produtos#create'
  patch 'produtos/:id', to: 'produtos#update'
  get 'produtos/new', to: 'produtos#new', as: :produto_new
  get 'produtos(/:id)', to: 'produtos#show', as: :produto_show
  get 'produtos/:id/edit', to: 'produtos#edit', as: :produto_edit
  get 'produtos/delproduto/:id', to: 'produtos#destroy', as: :produto_delete

  get 'produto/:produto_id/componentes_index', to: 'produtos#componentes_index', as: :componentes_index
  post 'produto/componentes((/:id1)(/:id2)(/:id3))', to: 'produtos#componentes_create'
  patch 'produto/componentes/:id1/:id2/:id3', to: 'produtos#componentes_update'
  get 'produto/componentes((/:id1)(/:id2)(/:id3))', to: 'produtos#componentes_show', as: :componentes_show
  get 'produtos/componentes_new', to: 'produtos#componentes_new', as: :componentes_new
  get 'produtos/componentes/:id1/:id2/:id3/edit', to: 'produtos#componentes_edit', as: :componentes_edit
  get 'produto/componentes/delcomponente/:id', to: 'produtos#componentes_destroy', as: :componentes_delete

end

app/controllers/compra_controller.rb
class CompraController < ApplicationController
  include ApplicationHelper
  before_action do redirecionar_privilegio(0) end
  before_action :set_vende, only: [:show, :edit, :update, :destroy]
  before_action :set_info, only: [:new, :show, :edit, :update, :create]
  before_action :set_item, only: [:item_show, :item_edit, :item_update, :item_destroy]
  
  # GET /vendes
  # GET /vendes.json
  def index
    @vendes = Vende.all
  end

  # GET /vendes/1
  # GET /vendes/1.json
  def show
    @vendes = Vende.find([params[:id1], params[:id2], params[:id3]])
  end

  # GET /vendes/new
  def new
	@modo_edicao = false
    @vende = Vende.new
  end

  # GET /vendes/1/edit
  def edit
    @modo_edicao = true
    @vende = Vende.find([params[:id1], params[:id2], params[:id3]])
  end
  
  # POST /vendes
  # POST /vendes.json
  def create
	if(params[:numero][:item].length <= 0)
		problema = 'É necessário definir uma quantidade para a compra.'
		redirect_to vende_new_path, notice: problema
		return
	end
	@vende = Vende.new(vende_params)
	@vende.fornecedor = @fornecedores[params[:selecao][:fornecedor].to_i]
	@vende.item = @item[params[:selecao][:item].to_i]
	
	respond_to do |format|
	  if @vende.save
        @vende.item.quantidade += params[:numero][:item].to_i
		@vende.item.save
		format.html { redirect_to item_index_path, notice: 'A compra foi registrada com sucesso.' }
        format.json { render :show, status: :created, location: @vende }
      else
        format.html { render :new }
        format.json { render json: @vende.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vendes/1
  # PATCH/PUT /vendes/1.json
  def update
    @vende = Vende.find([params[:id1], params[:id2], params[:id3]])
    respond_to do |format|
      if @vende.update(vende_params)
        format.html { redirect_to vende_show_path(@vende.idVende, @vende.idFornecedor, @vende.idItem), notice: 'A compra foi atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @vende }
      else
        format.html { render :edit }
        format.json { render json: @vende.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vendes/1
  # DELETE /vendes/1.json
  def destroy
    @vende = Vende.find([params[:id1],params[:id2],params[:id3]])
    @vende.destroy
    respond_to do |format|
      format.html { redirect_to vende_index_path, notice: 'A compra foi removida com sucesso.' }
      format.json { head :no_content }
    end
  end

  # GET /items
  # GET /items.json
  def item_index
    #@items = Item.all
  
	if (params[item_index_path].nil? ||
        params[item_index_path][:nome].empty?)
      nome = nil
    else
      nome = params[item_index_path][:nome]
    end
    if nome != nil
      @items = Item.where("nome like '%#{nome}%'")
    else
      @items = Item.all
    end
  end

  # GET /items/1
  # GET /items/1.json
  def item_show
    @item = Item.find(params[:id])
  end

  # GET /items/new
  def item_new
    @item = Item.new
  end

  # GET /items/1/edit
  def item_edit
    @item = Item.find(params[:id])
  end

  def relatorio_itens_falta
    @item = Item.where("quantidade < quantidadeMinima") 
  end

  # POST /items
  # POST /items.json
  def item_create
    @item = Item.new(item_params)
    respond_to do |format|
      if @item.save
        format.html { redirect_to item_index_path, notice: 'O item foi criado com sucesso.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :item_new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def item_update
    @item = Item.find(params[:id])
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to item_show_path(@item), notice: 'O item foi atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def item_destroy
    @item = Item.find(params[:id])
    @item.destroy
    respond_to do |format|
      format.html { redirect_to item_index_path, notice: 'O item foi removido com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vende
      @vende = Vende.find([params[:id1], params[:id2], params[:id3]])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vende_params
      params.require(:vende).permit(:idFornecedor, :idItem, :data, :valor)
	end
	
	def set_info
	  @fornecedores = Fornecedor.order(:nome)
	  @item = Item.order(:nome)
	end
	
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:nome, :marca, :descricao, :quantidade, :quantidadeMinima)
    end
end

app/helpers/compra_helper.rb
module CompraHelper
end

app/views/compra/_form.html.erb
<%I18n.locale = "br"%>
<p id="notice"><%= notice %></p>
<%= form_for(@vende , url: vende_show_path(@vende.idVende, @vende.idFornecedor, @vende.idItem)) do |f| %>
  <% if @vende.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vende.errors.count, "erro") %> impediram o sucesso da operacao:</h2>

      <ul>
      <% @vende.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%if(@print != nil)%>
  <%=@print%>
  <% end %>
  <div class="field">
    <%=Fornecedor%><br>
	<%@sid = -1%>
	<%=select("selecao", "fornecedor", @fornecedores.collect{|fornecedor| [fornecedor.nome, @sid = @sid+1]}, {include_blank: false})%>
  </div>
  <div class="field">
    <%=Item%><br>
	<%@sid = -1%>
	<%=select("selecao", "item", @item.collect{|item| [item.nome, @sid = @sid+1]}, {include_blank: false})=%>
  </div>
  <div class="field">
    <%= f.label :data %><br>
    <%= f.date_select :data%>
  </div>
  <br>
  <% if(not @modo_edicao) %>
    <div class="field">
      <%= "Quantidade de itens"%><br>
      <%= number_field("numero", "item", options = {min: 1, :class => "form-control input-small"}) %>
    </div>
  <% end%>
  <div class="field">
    <%= f.label :valor %><br>
    <%= f.number_field :valor ,:class => "form-control input-small"%>
  </div>
  <br>
  <div class="actions">
    <%= f.submit "Salvar", :class => "btn green" %>
  </div>
<% end %>

app/views/compra/_item_form.html.erb
<%= form_for(@item, url: item_show_path(@item)) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "erro") %> impediram o sucesso da operacao:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome, :class => "form-control input-medium" %>
  </div>
  <div class="field">
    <%= f.label :marca %><br>
    <%= f.text_field :marca, :class => "form-control input-medium" %>
  </div>
  <div class="field">
    <%= f.label :descrição %><br>
    <%= f.text_field :descricao, :class => "form-control input-medium" %>
  </div>
  <div class="field">
    <%= f.label :quantidade %><br>
    <%= f.number_field :quantidade, :class => "form-control input-small" %>
  </div>
  <div class="field">
    <%= f.label "Quantidade Mínima" %><br>
    <%= f.number_field :quantidadeMinima, :class => "form-control input-small"%>
  </div>
  <br>
  <div class="actions">
	<%= f.submit "Salvar", :class => 'btn green' %>
  </div>
<% end %>

app/views/compra/_item_table.html.erb
<table class="table table-hover">
  <thead>
    <tr>
	  <th>Nome</th>
      <th>Marca</th>
      <th>Quantidade</th>
      <th>Alerta</th>
      <th>Opções</th>
	  <th colspan="3"></th>
    </tr>
  </thead>
  <br>
  <tbody>
	
	<% @items.each do |item| %>
	 
	  <tr>
        <td><%= item.nome %></td>
        <td><%= item.marca %></td>
        <td><%= item.quantidade %></td>
        <td align = "center">
		  <% if(item.quantidade < item.quantidadeMinima) %><span class="glyphicon glyphicon-exclamation-sign" title="A quantidade de itens esta baixa"></span><% end %>
		</td>
        <td align = "right"> <a href = <%= item_show_path(item)%>> <span class="glyphicon glyphicon-log-in" title="Detalhes"> </a></td>
        <td align = "center"> <a href = <%= item_edit_path(item)%>> <span class="glyphicon glyphicon-edit" title="Modificar"> </a></td>
        <td align = "center"> <a href = <%= item_delete_path(item)%>> <span class="glyphicon glyphicon-remove" title="Remover"> </a></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/compra/edit.html.erb
<div class="portlet light">
	<div class="portlet-title">
		<div class="caption font-blue-sunglo">
			<span class="caption-subject bold uppercase">Modificando compra</span>
		</div>
	</div>
	<%= render 'form' %>

	<%= button_to 'Voltar', vende_index_path, :class => "btn btn-default", :method => :get  %><br>
</div>

app/views/compra/index.html.erb
<p id="notice"><%= notice %></p>

<div class="portlet light">
	<div class="portlet-title">
		<div class="caption font-blue-sunglo">
			<span class="caption-subject bold uppercase">Lista de compras de itens</span>
		</div>
	</div>

	<table class="table table-hover">
		<thead>
			<tr>
				<th>Código</th>
				<th>Data</th>
				<th>Valor</th>
				<th>Opções</th>
				<th colspan="3"></th>
			</tr>
		</thead>

		<tbody>
			<% @vendes.each do |vende| %>
				<tr>
					<td><%= vende.idVende %></td>
					<td><%= vende.data %></td>
					<td><%= vende.valor %></td>
					<td align = "right"> <a href = <%= vende_show_path(vende.idVende, vende.idFornecedor, vende.idItem)%>> <span class="glyphicon glyphicon-log-in" title="Detalhes"> </a></td>
					<td align = "center"> <a href = <%= vende_edit_path(vende.idVende, vende.idFornecedor, vende.idItem)%>> <span class="glyphicon glyphicon-edit" title="Modificar"> </a></td>
					<td align = "center"> <a href = <%= vende_delete_path(vende.idVende, vende.idFornecedor, vende.idItem)%>> <span class="glyphicon glyphicon-remove" title="Remover"> </a></td>
				</tr>
			<% end %>
		</tbody>
	</table>
	<br>
	<br>
	<%= button_to 'Voltar', item_index_path, :class => "btn btn-default", :method => :get  %><br>
</div>

app/views/compra/item_edit.html.erb
<div class="portlet light">
	<div class="portlet-title">
		<div class="caption font-blue-sunglo">
			<span class="caption-subject bold uppercase">Modificando item</span>
		</div>
	</div>
	
	<%= render 'item_form' %>

	<%= button_to 'Voltar', item_index_path, :class => "btn btn-default", :method => :get  %><br>
</div>

app/views/compra/item_index.html.erb
<p id="notice"><%= notice %></p>

<div class="portlet light">
	<div class="row">
		<div class="col-sm-5">
			<%= link_to item_new_path, class: "btn green", :method => :get do %>
				<i class="fa fa-plus-circle"></i>
				Cadastrar novo Item
			<% end %>
		</div>
		<div class="col-sm-5"><%= button_to "Relatório dos Itens em falta", itens_falta_relatorio_path, :class => "btn btn-default", :method => :get %></div>
	</div>
	<br>
	<div class="row">
		<div class="col-sm-5">
			<%= link_to vende_new_path, class: "btn green", :method => :get do %>
				<i class="fa fa-plus-circle"></i>
				Registrar compra de Itens
			<% end %>
		</div>
		<div class="col-sm-5"><%= button_to "Listar compras de itens", vende_index_path, :class => "btn btn-default", :method => :get  %></div>
		
	</div>
</div>

<div class="portlet light">
	<div class="portlet-title">
		<div class="caption font-blue-sunglo">
			<span class="caption-subject bold uppercase">Lista de Itens</span>
		</div>
	</div>
	<br>
	<%= form_for(item_index_path) do |f| %>
		<div class="col-md-4"> 
			<%= f.text_field :nome, placeholder: 'Digite o nome do item',class: "form-control" %>
		</div>
		<div class="actions">
			<%= f.submit "Consulta", class: "btn btn-default"%>
		</div>
	<%end%>
	
	<%= render partial: 'item_table', locals: {items: @items } %>
</div>

<br>
<br>

app/views/compra/item_new.html.erb
<div class="portlet light">
	<div class="portlet-title">
		<div class="caption font-blue-sunglo">
			<span class="caption-subject bold uppercase">Novo item</span>
		</div>
	</div>

	<%= render 'item_form' %>

	<%= button_to 'Voltar', item_index_path, :class => "btn btn-default", :method => :get  %><br>
</div>

app/views/compra/item_search.html.erb
<p id="notice"><%= notice %></p>

<h1>Consultando Itens</h1>

  <%= form_for(item_search_path) do |f| %>
  <div class="col-md-6">
    <%= f.label 'Nome:' %><br>
    <%= f.text_field :nome, class: "form-control" %>
  </div>
  <br/>
  <div class="actions">
    <%= f.submit "Consulta", class: "btn green"%>
  </div>

<% end %>

<%= render partial: 'item_table', locals: {items: @items } %>

<br>

app/views/compra/item_show.html.erb
<p id="notice"><%= notice %></p>

<div class="portlet light">
	<div class="portlet-title">
		<div class="caption font-blue-sunglo">
			<span class="caption-subject bold uppercase">Detalhes do item</span>
		</div>
	</div>

	<div class="field">
		<strong>Nome:</strong>
		<%= @item.nome %>
	</div>

	<div class="field">
		<strong>Marca:</strong>
		<%= @item.marca %>
	</div>

	<div class="field">
		<strong>Descrição:</strong>
		<%= @item.descricao %>
	</div>

	<div class="field">
		<strong>Quantidade:</strong>
		<%= @item.quantidade %>
	</div>

	<div class="field">
		<strong>Quantidade mínima:</strong>
		<%= @item.quantidadeMinima %>
	</div>
	<br>
	<%= button_to 'Modificar', item_edit_path(@item), :class => "btn blue", :method => :get  %><br>
	<%= button_to 'Voltar', item_index_path, :class => "btn btn-default", :method => :get  %><br>
</div>

app/views/compra/new.html.erb
<div class="portlet light">
	<div class="portlet-title">
		<div class="caption font-blue-sunglo">
			<span class="caption-subject bold uppercase">Registrar compra de itens</span>
		</div>
	</div>

	<%= render 'form' %>

	<%= button_to 'Voltar', item_index_path, :class => "btn btn-default", :method => :get  %><br>
</div>

app/views/compra/relatorio_itens_falta.html.erb
<% content_for :js do%>
  <%= javascript_tag do %>
    function printDiv(divName) {
      var printContents = document.getElementById(divName).innerHTML;
      var originalContents = document.body.innerHTML;

      document.body.innerHTML = printContents;

      window.print();

      document.body.innerHTML = originalContents;
    }
  <% end %>
<% end %>

<div class="portlet light">
	<div class="portlet-title">
		<div class="caption font-blue-sunglo">
			<span class="caption-subject bold uppercase">Lista de itens em falta</span>
		</div>
	</div>
	<%if @item.length == 0%>
		<p id="notice"><%= 'Não há itens em falta.' %></p>
	<%else%>
		<div id="print">
		<table class="table table-hover">
			<thead>
				<tr>
				<th>Nome</th>
				<th>Marca</th>
				<th>Quantidade</th>
				<th>Quantidade mínima</th>
				<th colspan="3"></th>
				</tr>
			</thead>
			<br>
			<tbody>
	
				<% @item.each do |item| %>
					<tr>
						<td><%= item.nome %></td>
						<td><%= item.marca %></td>
						<td><%= item.quantidade %></td>
						<td><%= item.quantidadeMinima %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
		</div>
	
		<br>
		<%= link_to 'Imprimir', '', class: "btn btn-default" ,onclick: 'printDiv("print")' %> <br>
	<%end%>
	<br>
	<%= button_to 'Voltar', item_index_path, :class => "btn btn-default", :method => :get  %><br>
</div>

app/views/compra/show.html.erb
<p id="notice"><%= notice %></p>
<div class="portlet light">
	<div class="portlet-title">
		<div class="caption font-blue-sunglo">
			<span class="caption-subject bold uppercase">Detalhes de compra</span>
		</div>
	</div>

	<br>


	<p>
		<strong>Código:</strong>
		<%= @vende.idVende %>
	</p>

	<p>
		<strong>Fornecedor:</strong>
		<%= Fornecedor.find(@vende.idFornecedor).nome %>
	</p>

	<p>
		<strong>Item:</strong>
		<%= (item = Item.find(@vende.idItem)).nome + " (" + item.marca + ")" %>
	</p>

	<p>
		<strong>Data:</strong>
		<%= @vende.data %>
	</p>

	<p>
		<strong>Valor:</strong>
		<%= @vende.valor %>
	</p>
	<br>

	<%= button_to 'Modificar', vende_edit_path(@vende.idVende, @vende.idFornecedor, @vende.idItem), :class => "btn blue", :method => :get  %><br>
	<%= button_to 'Voltar', vende_index_path, :class => "btn btn-default", :method => :get  %><br>

</div>